require("lazy").setup({
	spec = {
		"tpope/vim-sleuth",

		require("plugins/telescope"),
		require("plugins/treesitter"),
		require("plugins/lsp"),
		require("plugins/conform"),
		require("plugins/nvim-tree"),
		require("plugins/themery"),
		require("plugins/lualine"),
		require("plugins/scissors"),
		require("plugins/barbar"),
		require("plugins/devicons"),
		require("plugins/alpha"),
		require("plugins/neogen"),
		require("plugins/trouble"),
		require("plugins/undotree"),
		require("plugins/zenmode"),
		require("plugins/whichkey"),
		require("plugins/refactoring"),
		require("plugins/supermaven"),
		require("plugins/dap"),

		{ import = "themes" },
	},
	install = { colorscheme = { "habamax" } },
	checker = { enabled = true, notify = false },
--	ui = {
--		icons = {
--			cmd = "⌘",
--			config = "🛠",
--			event = "📅",
--			ft = "📂",
--			init = "⚙",
--			keys = "🗝",
--			plugin = "🔌",
--			runtime = "💻",
--			require = "🌙",
--			source = "📄",
--			start = "🚀",
--			task = "📌",
--			lazy = "💤 ",
--		},
--	},
})
